### ISSUE TITLE
Add definitions for all terms in COS

### ISSUE THREAD

**Issue by greatbacon** [feltcoop/felt#38]
Currently the five vocab terms of consentful systems that we reference are missing definitions, we should add those.

**Comment by ryanatkn** [comment]
see the `description` field here: https://github.com/feltcoop/felt/blob/main/src/consent/consent.ts

**Comment by greatbacon** [comment]
This should also probably include the proper credit for @trusttri 
`"This sketch is inspired by and the five principles of consent are from consentful.systems (research led by Jane Im)✨" `

& a call to action on the `End` screen to visit consentful.systems to learn more
