### ISSUE TITLE
COS - Take a second pass at the `Revertible` page

### ISSUE THREAD

**Issue by greatbacon** [feltcoop/felt#41]
In some of our discussions around `Revertible` we've brought up options (like maybe subscription options) that should be immediately reversible or maybe sections of the terms you should be able to opt out of.

**Comment by ryanatkn** [comment]
To keep it simple, I like the idea of referring back to the previous step -- the fact that you just accepted legal documents that you have no idea about. And you can't undo that, your account is ours now, you can only choose the nuclear option later on in settings or whatever.

**Comment by greatbacon** [comment]
Okay, I can dig that. So something like :

`informed`| <here's a big blog of leaglese that you just say yes to> | <here's the plain language terms, enumerated>

`revertible`| <if you change your mind or don't like what we're doing, you can only delete your account> | <here's the list of everything you just agreed to, but with checkboxes to opt out>

something like that?

**Comment by ryanatkn** [comment]
Yeah that's a good description. I can't picture checkboxes to opt out working, but I can see a button that's like, "I  don't want this delete everything now please"

**Comment by ryanatkn** [comment]
I think we got the gist here, kind of expecting more PRs but I think the main idea is in now.
