### ISSUE TITLE
COS - Add clarifying text to green progress checkmarks

### ISSUE THREAD

**Issue by greatbacon** [feltcoop/felt#76]
Currently, when a user completes one side of a vocab page, a green checkmark appears indicating they have completed it, but it is unclear that the other side of the screen needs to be completed to advance the sketch.

We should add some clarifying text to the component to indicate to users to complete to other side of the flow.

**Comment by ryanatkn** [comment]
What do you think of "now do this side to continue" with a pointing arrow?
